// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openproxy/agent/v1/agent.proto

// 版本一致时才用的消息：期望状态、状态上报、REALITY 目标检测与扫描。
// 可以随版本改动，但要保持线上兼容：不改字段编号和类型，删字段要 reserved。
// 见 docs/design-docs/protocol.md。

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyFailure_Item int32

const (
	ApplyFailure_ITEM_UNSPECIFIED ApplyFailure_Item = 0
	// id 是节点 ID。
	ApplyFailure_ITEM_NODE ApplyFailure_Item = 1
	// id 是出口 ID。
	ApplyFailure_ITEM_EXIT ApplyFailure_Item = 2
	// id 为 0。
	ApplyFailure_ITEM_LANDING ApplyFailure_Item = 3
	// id 为 0。
	ApplyFailure_ITEM_CERTIFICATE ApplyFailure_Item = 4
	// id 是节点 ID。
	ApplyFailure_ITEM_PORT_HOPPING ApplyFailure_Item = 5
)

// Enum value maps for ApplyFailure_Item.
var (
	ApplyFailure_Item_name = map[int32]string{
		0: "ITEM_UNSPECIFIED",
		1: "ITEM_NODE",
		2: "ITEM_EXIT",
		3: "ITEM_LANDING",
		4: "ITEM_CERTIFICATE",
		5: "ITEM_PORT_HOPPING",
	}
	ApplyFailure_Item_value = map[string]int32{
		"ITEM_UNSPECIFIED":  0,
		"ITEM_NODE":         1,
		"ITEM_EXIT":         2,
		"ITEM_LANDING":      3,
		"ITEM_CERTIFICATE":  4,
		"ITEM_PORT_HOPPING": 5,
	}
)

func (x ApplyFailure_Item) Enum() *ApplyFailure_Item {
	p := new(ApplyFailure_Item)
	*p = x
	return p
}

func (x ApplyFailure_Item) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplyFailure_Item) Descriptor() protoreflect.EnumDescriptor {
	return file_openproxy_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ApplyFailure_Item) Type() protoreflect.EnumType {
	return &file_openproxy_agent_v1_agent_proto_enumTypes[0]
}

func (x ApplyFailure_Item) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplyFailure_Item.Descriptor instead.
func (ApplyFailure_Item) EnumDescriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{13, 0}
}

// 主控给一台服务器的整份期望状态（推送）。Agent 逐项应用，然后发 StateReport。
// Agent 把它原样（protobuf 编码）保存在本地，启动时先按它启动。
type DesiredState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 单调递增：取「上一个版本 + 1」和当前毫秒时间戳中的大者。
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// 这台服务器上用得到的用户。
	Users []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Nodes []*Node `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Exits []*Exit `protobuf:"bytes,4,rep,name=exits,proto3" json:"exits,omitempty"`
	// 这台服务器当自建落地机时的 SOCKS5 入站；不当落地机时不设置。
	Landing *Landing `protobuf:"bytes,5,opt,name=landing,proto3" json:"landing,omitempty"`
	// TLS 节点（Hysteria2、AnyTLS）共用的证书；没有 TLS 节点时不设置。
	Certificate   *Certificate `protobuf:"bytes,6,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *DesiredState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DesiredState) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *DesiredState) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DesiredState) GetExits() []*Exit {
	if x != nil {
		return x.Exits
	}
	return nil
}

func (x *DesiredState) GetLanding() *Landing {
	if x != nil {
		return x.Landing
	}
	return nil
}

func (x *DesiredState) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

// 一个用户的凭据，所有节点通用。
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID；它的十进制字符串就是 sing-box 和 Mieru 里的用户名。
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// VLESS 用。
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Hysteria2、AnyTLS、Mieru 用。
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Shadowsocks 2022 的用户密钥（base64），长度符合加密方式。
	SsKey         string `protobuf:"bytes,4,opt,name=ss_key,json=ssKey,proto3" json:"ss_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetSsKey() string {
	if x != nil {
		return x.SsKey
	}
	return ""
}

// 一个节点就是一个入站，入站 tag 是 "node-<id>"。
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Port  uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// 能用这个节点的用户，引用 DesiredState.users 里的 ID。
	// 追踪层只放行这里列出的用户：用户被移除后立即断开，不等入站重建。
	UserIds []uint64 `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// 流量走哪个落地出口，引用 DesiredState.exits 里的 ID；0 表示直连。
	ExitId uint64 `protobuf:"varint,4,opt,name=exit_id,json=exitId,proto3" json:"exit_id,omitempty"`
	// Types that are valid to be assigned to Protocol:
	//
	//	*Node_VlessReality
	//	*Node_Hysteria2
	//	*Node_Anytls
	//	*Node_Shadowsocks2022
	//	*Node_Mieru
	Protocol      isNode_Protocol `protobuf_oneof:"protocol"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Node) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Node) GetExitId() uint64 {
	if x != nil {
		return x.ExitId
	}
	return 0
}

func (x *Node) GetProtocol() isNode_Protocol {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *Node) GetVlessReality() *VlessReality {
	if x != nil {
		if x, ok := x.Protocol.(*Node_VlessReality); ok {
			return x.VlessReality
		}
	}
	return nil
}

func (x *Node) GetHysteria2() *Hysteria2 {
	if x != nil {
		if x, ok := x.Protocol.(*Node_Hysteria2); ok {
			return x.Hysteria2
		}
	}
	return nil
}

func (x *Node) GetAnytls() *AnyTls {
	if x != nil {
		if x, ok := x.Protocol.(*Node_Anytls); ok {
			return x.Anytls
		}
	}
	return nil
}

func (x *Node) GetShadowsocks2022() *Shadowsocks2022 {
	if x != nil {
		if x, ok := x.Protocol.(*Node_Shadowsocks2022); ok {
			return x.Shadowsocks2022
		}
	}
	return nil
}

func (x *Node) GetMieru() *Mieru {
	if x != nil {
		if x, ok := x.Protocol.(*Node_Mieru); ok {
			return x.Mieru
		}
	}
	return nil
}

type isNode_Protocol interface {
	isNode_Protocol()
}

type Node_VlessReality struct {
	VlessReality *VlessReality `protobuf:"bytes,10,opt,name=vless_reality,json=vlessReality,proto3,oneof"`
}

type Node_Hysteria2 struct {
	Hysteria2 *Hysteria2 `protobuf:"bytes,11,opt,name=hysteria2,proto3,oneof"`
}

type Node_Anytls struct {
	Anytls *AnyTls `protobuf:"bytes,12,opt,name=anytls,proto3,oneof"`
}

type Node_Shadowsocks2022 struct {
	Shadowsocks2022 *Shadowsocks2022 `protobuf:"bytes,13,opt,name=shadowsocks2022,proto3,oneof"`
}

type Node_Mieru struct {
	Mieru *Mieru `protobuf:"bytes,14,opt,name=mieru,proto3,oneof"`
}

func (*Node_VlessReality) isNode_Protocol() {}

func (*Node_Hysteria2) isNode_Protocol() {}

func (*Node_Anytls) isNode_Protocol() {}

func (*Node_Shadowsocks2022) isNode_Protocol() {}

func (*Node_Mieru) isNode_Protocol() {}

// VLESS + REALITY：传输 TCP，flow 固定为 xtls-rprx-vision。
type VlessReality struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// X25519 私钥，base64 raw url 编码。
	PrivateKey string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	ShortIds   []string `protobuf:"bytes,2,rep,name=short_ids,json=shortIds,proto3" json:"short_ids,omitempty"`
	// 伪装目标，同时作为 server_name。
	TargetHost    string `protobuf:"bytes,3,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    uint32 `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlessReality) Reset() {
	*x = VlessReality{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessReality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessReality) ProtoMessage() {}

func (x *VlessReality) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessReality.ProtoReflect.Descriptor instead.
func (*VlessReality) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *VlessReality) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *VlessReality) GetShortIds() []string {
	if x != nil {
		return x.ShortIds
	}
	return nil
}

func (x *VlessReality) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *VlessReality) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

// Hysteria2：使用 DesiredState.certificate。
type Hysteria2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// salamander 混淆密码；为空表示不开混淆。
	ObfsPassword string `protobuf:"bytes,1,opt,name=obfs_password,json=obfsPassword,proto3" json:"obfs_password,omitempty"`
	// 端口跳跃范围，Agent 用 nftables 转发到节点端口；不设置表示不开。
	PortHopping   *PortRange `protobuf:"bytes,2,opt,name=port_hopping,json=portHopping,proto3" json:"port_hopping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hysteria2) Reset() {
	*x = Hysteria2{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hysteria2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hysteria2) ProtoMessage() {}

func (x *Hysteria2) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hysteria2.ProtoReflect.Descriptor instead.
func (*Hysteria2) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Hysteria2) GetObfsPassword() string {
	if x != nil {
		return x.ObfsPassword
	}
	return ""
}

func (x *Hysteria2) GetPortHopping() *PortRange {
	if x != nil {
		return x.PortHopping
	}
	return nil
}

// 闭区间 [start, end]。
type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PortRange) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PortRange) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// AnyTLS：只用 TLS，使用 DesiredState.certificate。
type AnyTls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyTls) Reset() {
	*x = AnyTls{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyTls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyTls) ProtoMessage() {}

func (x *AnyTls) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyTls.ProtoReflect.Descriptor instead.
func (*AnyTls) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

// Shadowsocks 2022，多用户。
type Shadowsocks2022 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目前固定为 "2022-blake3-aes-128-gcm"。
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// 服务端主密钥（base64）。
	ServerKey     string `protobuf:"bytes,2,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shadowsocks2022) Reset() {
	*x = Shadowsocks2022{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shadowsocks2022) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shadowsocks2022) ProtoMessage() {}

func (x *Shadowsocks2022) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shadowsocks2022.ProtoReflect.Descriptor instead.
func (*Shadowsocks2022) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Shadowsocks2022) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Shadowsocks2022) GetServerKey() string {
	if x != nil {
		return x.ServerKey
	}
	return ""
}

// Mieru：传输 TCP。
type Mieru struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mieru) Reset() {
	*x = Mieru{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mieru) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mieru) ProtoMessage() {}

func (x *Mieru) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mieru.ProtoReflect.Descriptor instead.
func (*Mieru) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

// 落地出口：一个 SOCKS5 出站，tag 是 "exit-<id>"。
type Exit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exit) Reset() {
	*x = Exit{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exit) ProtoMessage() {}

func (x *Exit) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exit.ProtoReflect.Descriptor instead.
func (*Exit) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Exit) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exit) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Exit) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Exit) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Exit) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 自建落地机上的 SOCKS5 入站。
type Landing struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Port     uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// 只放行这些来源 IP（用这台落地的节点服务器）；主控生成状态时把服务器地址解析成 IP。
	AllowedSourceIps []string `protobuf:"bytes,4,rep,name=allowed_source_ips,json=allowedSourceIps,proto3" json:"allowed_source_ips,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Landing) Reset() {
	*x = Landing{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Landing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Landing) ProtoMessage() {}

func (x *Landing) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Landing.ProtoReflect.Descriptor instead.
func (*Landing) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Landing) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Landing) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Landing) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Landing) GetAllowedSourceIps() []string {
	if x != nil {
		return x.AllowedSourceIps
	}
	return nil
}

// PEM 格式的证书和私钥：有域名的是主控申请的正式证书，没有域名的是主控生成的自签证书。
type Certificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 证书链，服务器证书在前。
	CertPem       string `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem        string `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Certificate) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *Certificate) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

// Agent 应用完一份期望状态后的报告（推送）。连接成功、同步开始时也发一次。
type StateReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 已经处理完的期望状态版本（含失败项），不表示全部成功。
	AppliedVersion uint64 `protobuf:"varint,1,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	// 应用失败的项：这些项保持原样，其他项照常生效。
	Failures      []*ApplyFailure `protobuf:"bytes,2,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateReport) Reset() {
	*x = StateReport{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReport) ProtoMessage() {}

func (x *StateReport) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReport.ProtoReflect.Descriptor instead.
func (*StateReport) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StateReport) GetAppliedVersion() uint64 {
	if x != nil {
		return x.AppliedVersion
	}
	return 0
}

func (x *StateReport) GetFailures() []*ApplyFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

// 一项应用失败。
type ApplyFailure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Item  ApplyFailure_Item      `protobuf:"varint,1,opt,name=item,proto3,enum=openproxy.agent.v1.ApplyFailure_Item" json:"item,omitempty"`
	Id    uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// 给管理员看的原因，例如「端口 443 被占用」。
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFailure) Reset() {
	*x = ApplyFailure{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFailure) ProtoMessage() {}

func (x *ApplyFailure) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFailure.ProtoReflect.Descriptor instead.
func (*ApplyFailure) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyFailure) GetItem() ApplyFailure_Item {
	if x != nil {
		return x.Item
	}
	return ApplyFailure_ITEM_UNSPECIFIED
}

func (x *ApplyFailure) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApplyFailure) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 检测管理员选中的 REALITY 伪装目标（请求，超时 1 分钟）。
type CheckRealityTargets struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "host" 或 "host:port"，不写端口时是 443。
	Targets       []string `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRealityTargets) Reset() {
	*x = CheckRealityTargets{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRealityTargets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRealityTargets) ProtoMessage() {}

func (x *CheckRealityTargets) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRealityTargets.ProtoReflect.Descriptor instead.
func (*CheckRealityTargets) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CheckRealityTargets) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

// Agent 对 CheckRealityTargets 的回复。
type CheckRealityTargetsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RealityTargetCheck  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRealityTargetsResult) Reset() {
	*x = CheckRealityTargetsResult{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRealityTargetsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRealityTargetsResult) ProtoMessage() {}

func (x *CheckRealityTargetsResult) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRealityTargetsResult.ProtoReflect.Descriptor instead.
func (*CheckRealityTargetsResult) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CheckRealityTargetsResult) GetResults() []*RealityTargetCheck {
	if x != nil {
		return x.Results
	}
	return nil
}

// 一个目标的检测结果，在节点服务器上测得。
type RealityTargetCheck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Target           string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Tls13            bool                   `protobuf:"varint,2,opt,name=tls13,proto3" json:"tls13,omitempty"`
	H2               bool                   `protobuf:"varint,3,opt,name=h2,proto3" json:"h2,omitempty"`
	LatencyMs        uint32                 `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CertificateValid bool                   `protobuf:"varint,5,opt,name=certificate_valid,json=certificateValid,proto3" json:"certificate_valid,omitempty"`
	// 连不上等错误；为空表示检测完成，看上面几项。
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealityTargetCheck) Reset() {
	*x = RealityTargetCheck{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealityTargetCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealityTargetCheck) ProtoMessage() {}

func (x *RealityTargetCheck) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealityTargetCheck.ProtoReflect.Descriptor instead.
func (*RealityTargetCheck) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *RealityTargetCheck) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RealityTargetCheck) GetTls13() bool {
	if x != nil {
		return x.Tls13
	}
	return false
}

func (x *RealityTargetCheck) GetH2() bool {
	if x != nil {
		return x.H2
	}
	return false
}

func (x *RealityTargetCheck) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RealityTargetCheck) GetCertificateValid() bool {
	if x != nil {
		return x.CertificateValid
	}
	return false
}

func (x *RealityTargetCheck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 在服务器上扫描可用的 REALITY 伪装目标（请求，超时 20 分钟）。慢速、低并发。
type ScanRealityTargets struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要扫的网段，例如 "203.0.113.0/24"。
	Cidr string `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	// 同时扫描的地址数。
	Concurrency uint32 `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// 每秒最多发起的连接数。
	MaxPerSecond  uint32 `protobuf:"varint,3,opt,name=max_per_second,json=maxPerSecond,proto3" json:"max_per_second,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRealityTargets) Reset() {
	*x = ScanRealityTargets{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRealityTargets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRealityTargets) ProtoMessage() {}

func (x *ScanRealityTargets) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRealityTargets.ProtoReflect.Descriptor instead.
func (*ScanRealityTargets) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ScanRealityTargets) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *ScanRealityTargets) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *ScanRealityTargets) GetMaxPerSecond() uint32 {
	if x != nil {
		return x.MaxPerSecond
	}
	return 0
}

// Agent 对 ScanRealityTargets 的回复，扫描结束时一次性返回。整体失败时改回 ErrorReply。
type ScanRealityTargetsResult struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Candidates    []*RealityScanCandidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRealityTargetsResult) Reset() {
	*x = ScanRealityTargetsResult{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRealityTargetsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRealityTargetsResult) ProtoMessage() {}

func (x *ScanRealityTargetsResult) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRealityTargetsResult.ProtoReflect.Descriptor instead.
func (*ScanRealityTargetsResult) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ScanRealityTargetsResult) GetCandidates() []*RealityScanCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// 一个支持 TLS 1.3 和 H2 的候选目标。
type RealityScanCandidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ip    string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// 证书里的域名。
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// 证书签发者。
	Issuer        string `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	LatencyMs     uint32 `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealityScanCandidate) Reset() {
	*x = RealityScanCandidate{}
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealityScanCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealityScanCandidate) ProtoMessage() {}

func (x *RealityScanCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealityScanCandidate.ProtoReflect.Descriptor instead.
func (*RealityScanCandidate) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *RealityScanCandidate) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RealityScanCandidate) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RealityScanCandidate) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *RealityScanCandidate) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_openproxy_agent_v1_agent_proto protoreflect.FileDescriptor

const file_openproxy_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1eopenproxy/agent/v1/agent.proto\x12\x12openproxy.agent.v1\"\xb2\x02\n" +
	"\fDesiredState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12.\n" +
	"\x05users\x18\x02 \x03(\v2\x18.openproxy.agent.v1.UserR\x05users\x12.\n" +
	"\x05nodes\x18\x03 \x03(\v2\x18.openproxy.agent.v1.NodeR\x05nodes\x12.\n" +
	"\x05exits\x18\x04 \x03(\v2\x18.openproxy.agent.v1.ExitR\x05exits\x125\n" +
	"\alanding\x18\x05 \x01(\v2\x1b.openproxy.agent.v1.LandingR\alanding\x12A\n" +
	"\vcertificate\x18\x06 \x01(\v2\x1f.openproxy.agent.v1.CertificateR\vcertificate\"]\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x15\n" +
	"\x06ss_key\x18\x04 \x01(\tR\x05ssKey\"\xac\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\x04R\auserIds\x12\x17\n" +
	"\aexit_id\x18\x04 \x01(\x04R\x06exitId\x12G\n" +
	"\rvless_reality\x18\n" +
	" \x01(\v2 .openproxy.agent.v1.VlessRealityH\x00R\fvlessReality\x12=\n" +
	"\thysteria2\x18\v \x01(\v2\x1d.openproxy.agent.v1.Hysteria2H\x00R\thysteria2\x124\n" +
	"\x06anytls\x18\f \x01(\v2\x1a.openproxy.agent.v1.AnyTlsH\x00R\x06anytls\x12O\n" +
	"\x0fshadowsocks2022\x18\r \x01(\v2#.openproxy.agent.v1.Shadowsocks2022H\x00R\x0fshadowsocks2022\x121\n" +
	"\x05mieru\x18\x0e \x01(\v2\x19.openproxy.agent.v1.MieruH\x00R\x05mieruB\n" +
	"\n" +
	"\bprotocol\"\x8e\x01\n" +
	"\fVlessReality\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1b\n" +
	"\tshort_ids\x18\x02 \x03(\tR\bshortIds\x12\x1f\n" +
	"\vtarget_host\x18\x03 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\rR\n" +
	"targetPort\"r\n" +
	"\tHysteria2\x12#\n" +
	"\robfs_password\x18\x01 \x01(\tR\fobfsPassword\x12@\n" +
	"\fport_hopping\x18\x02 \x01(\v2\x1d.openproxy.agent.v1.PortRangeR\vportHopping\"3\n" +
	"\tPortRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\"\b\n" +
	"\x06AnyTls\"H\n" +
	"\x0fShadowsocks2022\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"server_key\x18\x02 \x01(\tR\tserverKey\"\a\n" +
	"\x05Mieru\"v\n" +
	"\x04Exit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\x83\x01\n" +
	"\aLanding\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12,\n" +
	"\x12allowed_source_ips\x18\x04 \x03(\tR\x10allowedSourceIps\"A\n" +
	"\vCertificate\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\tR\x06keyPem\"t\n" +
	"\vStateReport\x12'\n" +
	"\x0fapplied_version\x18\x01 \x01(\x04R\x0eappliedVersion\x12<\n" +
	"\bfailures\x18\x02 \x03(\v2 .openproxy.agent.v1.ApplyFailureR\bfailures\"\xec\x01\n" +
	"\fApplyFailure\x129\n" +
	"\x04item\x18\x01 \x01(\x0e2%.openproxy.agent.v1.ApplyFailure.ItemR\x04item\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"y\n" +
	"\x04Item\x12\x14\n" +
	"\x10ITEM_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tITEM_NODE\x10\x01\x12\r\n" +
	"\tITEM_EXIT\x10\x02\x12\x10\n" +
	"\fITEM_LANDING\x10\x03\x12\x14\n" +
	"\x10ITEM_CERTIFICATE\x10\x04\x12\x15\n" +
	"\x11ITEM_PORT_HOPPING\x10\x05\"/\n" +
	"\x13CheckRealityTargets\x12\x18\n" +
	"\atargets\x18\x01 \x03(\tR\atargets\"]\n" +
	"\x19CheckRealityTargetsResult\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.openproxy.agent.v1.RealityTargetCheckR\aresults\"\xb4\x01\n" +
	"\x12RealityTargetCheck\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05tls13\x18\x02 \x01(\bR\x05tls13\x12\x0e\n" +
	"\x02h2\x18\x03 \x01(\bR\x02h2\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\rR\tlatencyMs\x12+\n" +
	"\x11certificate_valid\x18\x05 \x01(\bR\x10certificateValid\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"p\n" +
	"\x12ScanRealityTargets\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\rR\vconcurrency\x12$\n" +
	"\x0emax_per_second\x18\x03 \x01(\rR\fmaxPerSecond\"d\n" +
	"\x18ScanRealityTargetsResult\x12H\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2(.openproxy.agent.v1.RealityScanCandidateR\n" +
	"candidates\"u\n" +
	"\x14RealityScanCandidate\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\rR\tlatencyMsB\xda\x01\n" +
	"\x16com.openproxy.agent.v1B\n" +
	"AgentProtoP\x01ZJgithub.com/yuuuki-creation/open-proxy/agent/internal/pb/openproxy/agent/v1;agentv1\xa2\x02\x03OAX\xaa\x02\x12Openproxy.Agent.V1\xca\x02\x12Openproxy\\Agent\\V1\xe2\x02\x1eOpenproxy\\Agent\\V1\\GPBMetadata\xea\x02\x14Openproxy::Agent::V1b\x06proto3"

var (
	file_openproxy_agent_v1_agent_proto_rawDescOnce sync.Once
	file_openproxy_agent_v1_agent_proto_rawDescData []byte
)

func file_openproxy_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_openproxy_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_openproxy_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openproxy_agent_v1_agent_proto_rawDesc), len(file_openproxy_agent_v1_agent_proto_rawDesc)))
	})
	return file_openproxy_agent_v1_agent_proto_rawDescData
}

var file_openproxy_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openproxy_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_openproxy_agent_v1_agent_proto_goTypes = []any{
	(ApplyFailure_Item)(0),            // 0: openproxy.agent.v1.ApplyFailure.Item
	(*DesiredState)(nil),              // 1: openproxy.agent.v1.DesiredState
	(*User)(nil),                      // 2: openproxy.agent.v1.User
	(*Node)(nil),                      // 3: openproxy.agent.v1.Node
	(*VlessReality)(nil),              // 4: openproxy.agent.v1.VlessReality
	(*Hysteria2)(nil),                 // 5: openproxy.agent.v1.Hysteria2
	(*PortRange)(nil),                 // 6: openproxy.agent.v1.PortRange
	(*AnyTls)(nil),                    // 7: openproxy.agent.v1.AnyTls
	(*Shadowsocks2022)(nil),           // 8: openproxy.agent.v1.Shadowsocks2022
	(*Mieru)(nil),                     // 9: openproxy.agent.v1.Mieru
	(*Exit)(nil),                      // 10: openproxy.agent.v1.Exit
	(*Landing)(nil),                   // 11: openproxy.agent.v1.Landing
	(*Certificate)(nil),               // 12: openproxy.agent.v1.Certificate
	(*StateReport)(nil),               // 13: openproxy.agent.v1.StateReport
	(*ApplyFailure)(nil),              // 14: openproxy.agent.v1.ApplyFailure
	(*CheckRealityTargets)(nil),       // 15: openproxy.agent.v1.CheckRealityTargets
	(*CheckRealityTargetsResult)(nil), // 16: openproxy.agent.v1.CheckRealityTargetsResult
	(*RealityTargetCheck)(nil),        // 17: openproxy.agent.v1.RealityTargetCheck
	(*ScanRealityTargets)(nil),        // 18: openproxy.agent.v1.ScanRealityTargets
	(*ScanRealityTargetsResult)(nil),  // 19: openproxy.agent.v1.ScanRealityTargetsResult
	(*RealityScanCandidate)(nil),      // 20: openproxy.agent.v1.RealityScanCandidate
}
var file_openproxy_agent_v1_agent_proto_depIdxs = []int32{
	2,  // 0: openproxy.agent.v1.DesiredState.users:type_name -> openproxy.agent.v1.User
	3,  // 1: openproxy.agent.v1.DesiredState.nodes:type_name -> openproxy.agent.v1.Node
	10, // 2: openproxy.agent.v1.DesiredState.exits:type_name -> openproxy.agent.v1.Exit
	11, // 3: openproxy.agent.v1.DesiredState.landing:type_name -> openproxy.agent.v1.Landing
	12, // 4: openproxy.agent.v1.DesiredState.certificate:type_name -> openproxy.agent.v1.Certificate
	4,  // 5: openproxy.agent.v1.Node.vless_reality:type_name -> openproxy.agent.v1.VlessReality
	5,  // 6: openproxy.agent.v1.Node.hysteria2:type_name -> openproxy.agent.v1.Hysteria2
	7,  // 7: openproxy.agent.v1.Node.anytls:type_name -> openproxy.agent.v1.AnyTls
	8,  // 8: openproxy.agent.v1.Node.shadowsocks2022:type_name -> openproxy.agent.v1.Shadowsocks2022
	9,  // 9: openproxy.agent.v1.Node.mieru:type_name -> openproxy.agent.v1.Mieru
	6,  // 10: openproxy.agent.v1.Hysteria2.port_hopping:type_name -> openproxy.agent.v1.PortRange
	14, // 11: openproxy.agent.v1.StateReport.failures:type_name -> openproxy.agent.v1.ApplyFailure
	0,  // 12: openproxy.agent.v1.ApplyFailure.item:type_name -> openproxy.agent.v1.ApplyFailure.Item
	17, // 13: openproxy.agent.v1.CheckRealityTargetsResult.results:type_name -> openproxy.agent.v1.RealityTargetCheck
	20, // 14: openproxy.agent.v1.ScanRealityTargetsResult.candidates:type_name -> openproxy.agent.v1.RealityScanCandidate
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_openproxy_agent_v1_agent_proto_init() }
func file_openproxy_agent_v1_agent_proto_init() {
	if File_openproxy_agent_v1_agent_proto != nil {
		return
	}
	file_openproxy_agent_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*Node_VlessReality)(nil),
		(*Node_Hysteria2)(nil),
		(*Node_Anytls)(nil),
		(*Node_Shadowsocks2022)(nil),
		(*Node_Mieru)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openproxy_agent_v1_agent_proto_rawDesc), len(file_openproxy_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openproxy_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_openproxy_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_openproxy_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_openproxy_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_openproxy_agent_v1_agent_proto = out.File
	file_openproxy_agent_v1_agent_proto_goTypes = nil
	file_openproxy_agent_v1_agent_proto_depIdxs = nil
}
