// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openproxy/agent/v1/envelope.proto

// 两个方向的外壳：WebSocket 的每个二进制帧是一条外壳消息。
// 外壳属于稳定消息，规则同 stable.proto。

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent 发给主控的消息。
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 发送方自增的消息 ID，从 1 开始；两个方向各自计数。
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 回复时填对方那条请求的 id；不是回复填 0。
	ReplyTo uint64 `protobuf:"varint,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// 编号 10–99 给稳定消息，100 起给其他消息。
	//
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_UpgradeResult
	//	*AgentMessage_UninstallResult
	//	*AgentMessage_TrafficReport
	//	*AgentMessage_ErrorReply
	//	*AgentMessage_StateReport
	//	*AgentMessage_CheckRealityTargetsResult
	//	*AgentMessage_ScanRealityTargetsResult
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_openproxy_agent_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgentMessage) GetReplyTo() uint64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetUpgradeResult() *UpgradeResult {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_UpgradeResult); ok {
			return x.UpgradeResult
		}
	}
	return nil
}

func (x *AgentMessage) GetUninstallResult() *UninstallResult {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_UninstallResult); ok {
			return x.UninstallResult
		}
	}
	return nil
}

func (x *AgentMessage) GetTrafficReport() *TrafficReport {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_TrafficReport); ok {
			return x.TrafficReport
		}
	}
	return nil
}

func (x *AgentMessage) GetErrorReply() *ErrorReply {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ErrorReply); ok {
			return x.ErrorReply
		}
	}
	return nil
}

func (x *AgentMessage) GetStateReport() *StateReport {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_StateReport); ok {
			return x.StateReport
		}
	}
	return nil
}

func (x *AgentMessage) GetCheckRealityTargetsResult() *CheckRealityTargetsResult {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_CheckRealityTargetsResult); ok {
			return x.CheckRealityTargetsResult
		}
	}
	return nil
}

func (x *AgentMessage) GetScanRealityTargetsResult() *ScanRealityTargetsResult {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ScanRealityTargetsResult); ok {
			return x.ScanRealityTargetsResult
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type AgentMessage_UpgradeResult struct {
	UpgradeResult *UpgradeResult `protobuf:"bytes,11,opt,name=upgrade_result,json=upgradeResult,proto3,oneof"`
}

type AgentMessage_UninstallResult struct {
	UninstallResult *UninstallResult `protobuf:"bytes,12,opt,name=uninstall_result,json=uninstallResult,proto3,oneof"`
}

type AgentMessage_TrafficReport struct {
	TrafficReport *TrafficReport `protobuf:"bytes,13,opt,name=traffic_report,json=trafficReport,proto3,oneof"`
}

type AgentMessage_ErrorReply struct {
	ErrorReply *ErrorReply `protobuf:"bytes,14,opt,name=error_reply,json=errorReply,proto3,oneof"`
}

type AgentMessage_StateReport struct {
	StateReport *StateReport `protobuf:"bytes,100,opt,name=state_report,json=stateReport,proto3,oneof"`
}

type AgentMessage_CheckRealityTargetsResult struct {
	CheckRealityTargetsResult *CheckRealityTargetsResult `protobuf:"bytes,101,opt,name=check_reality_targets_result,json=checkRealityTargetsResult,proto3,oneof"`
}

type AgentMessage_ScanRealityTargetsResult struct {
	ScanRealityTargetsResult *ScanRealityTargetsResult `protobuf:"bytes,102,opt,name=scan_reality_targets_result,json=scanRealityTargetsResult,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Body() {}

func (*AgentMessage_UpgradeResult) isAgentMessage_Body() {}

func (*AgentMessage_UninstallResult) isAgentMessage_Body() {}

func (*AgentMessage_TrafficReport) isAgentMessage_Body() {}

func (*AgentMessage_ErrorReply) isAgentMessage_Body() {}

func (*AgentMessage_StateReport) isAgentMessage_Body() {}

func (*AgentMessage_CheckRealityTargetsResult) isAgentMessage_Body() {}

func (*AgentMessage_ScanRealityTargetsResult) isAgentMessage_Body() {}

// 主控发给 Agent 的消息。
type MasterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 发送方自增的消息 ID，从 1 开始；两个方向各自计数。
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 回复时填对方那条请求的 id；不是回复填 0。
	ReplyTo uint64 `protobuf:"varint,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// 编号 10–99 给稳定消息，100 起给其他消息。
	//
	// Types that are valid to be assigned to Body:
	//
	//	*MasterMessage_HelloResult
	//	*MasterMessage_Upgrade
	//	*MasterMessage_Uninstall
	//	*MasterMessage_ErrorReply
	//	*MasterMessage_DesiredState
	//	*MasterMessage_CheckRealityTargets
	//	*MasterMessage_ScanRealityTargets
	Body          isMasterMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_openproxy_agent_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *MasterMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MasterMessage) GetReplyTo() uint64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *MasterMessage) GetBody() isMasterMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MasterMessage) GetHelloResult() *HelloResult {
	if x != nil {
		if x, ok := x.Body.(*MasterMessage_HelloResult); ok {
			return x.HelloResult
		}
	}
	return nil
}

func (x *MasterMessage) GetUpgrade() *Upgrade {
	if x != nil {
		if x, ok := x.Body.(*MasterMessage_Upgrade); ok {
			return x.Upgrade
		}
	}
	return nil
}

func (x *MasterMessage) GetUninstall() *Uninstall {
	if x != nil {
		if x, ok := x.Body.(*MasterMessage_Uninstall); ok {
			return x.Uninstall
		}
	}
	return nil
}

func (x *MasterMessage) GetErrorReply() *ErrorReply {
	if x != nil {
		if x, ok := x.Body.(*MasterMessage_ErrorReply); ok {
			return x.ErrorReply
		}
	}
	return nil
}

func (x *MasterMessage) GetDesiredState() *DesiredState {
	if x != nil {
		if x, ok := x.Body.(*MasterMessage_DesiredState); ok {
			return x.DesiredState
		}
	}
	return nil
}

func (x *MasterMessage) GetCheckRealityTargets() *CheckRealityTargets {
	if x != nil {
		if x, ok := x.Body.(*MasterMessage_CheckRealityTargets); ok {
			return x.CheckRealityTargets
		}
	}
	return nil
}

func (x *MasterMessage) GetScanRealityTargets() *ScanRealityTargets {
	if x != nil {
		if x, ok := x.Body.(*MasterMessage_ScanRealityTargets); ok {
			return x.ScanRealityTargets
		}
	}
	return nil
}

type isMasterMessage_Body interface {
	isMasterMessage_Body()
}

type MasterMessage_HelloResult struct {
	HelloResult *HelloResult `protobuf:"bytes,10,opt,name=hello_result,json=helloResult,proto3,oneof"`
}

type MasterMessage_Upgrade struct {
	Upgrade *Upgrade `protobuf:"bytes,11,opt,name=upgrade,proto3,oneof"`
}

type MasterMessage_Uninstall struct {
	Uninstall *Uninstall `protobuf:"bytes,12,opt,name=uninstall,proto3,oneof"`
}

type MasterMessage_ErrorReply struct {
	ErrorReply *ErrorReply `protobuf:"bytes,13,opt,name=error_reply,json=errorReply,proto3,oneof"`
}

type MasterMessage_DesiredState struct {
	DesiredState *DesiredState `protobuf:"bytes,100,opt,name=desired_state,json=desiredState,proto3,oneof"`
}

type MasterMessage_CheckRealityTargets struct {
	CheckRealityTargets *CheckRealityTargets `protobuf:"bytes,101,opt,name=check_reality_targets,json=checkRealityTargets,proto3,oneof"`
}

type MasterMessage_ScanRealityTargets struct {
	ScanRealityTargets *ScanRealityTargets `protobuf:"bytes,102,opt,name=scan_reality_targets,json=scanRealityTargets,proto3,oneof"`
}

func (*MasterMessage_HelloResult) isMasterMessage_Body() {}

func (*MasterMessage_Upgrade) isMasterMessage_Body() {}

func (*MasterMessage_Uninstall) isMasterMessage_Body() {}

func (*MasterMessage_ErrorReply) isMasterMessage_Body() {}

func (*MasterMessage_DesiredState) isMasterMessage_Body() {}

func (*MasterMessage_CheckRealityTargets) isMasterMessage_Body() {}

func (*MasterMessage_ScanRealityTargets) isMasterMessage_Body() {}

var File_openproxy_agent_v1_envelope_proto protoreflect.FileDescriptor

const file_openproxy_agent_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"!openproxy/agent/v1/envelope.proto\x12\x12openproxy.agent.v1\x1a\x1eopenproxy/agent/v1/agent.proto\x1a\x1fopenproxy/agent/v1/stable.proto\"\xc8\x05\n" +
	"\fAgentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\breply_to\x18\x02 \x01(\x04R\areplyTo\x121\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x19.openproxy.agent.v1.HelloH\x00R\x05hello\x12J\n" +
	"\x0eupgrade_result\x18\v \x01(\v2!.openproxy.agent.v1.UpgradeResultH\x00R\rupgradeResult\x12P\n" +
	"\x10uninstall_result\x18\f \x01(\v2#.openproxy.agent.v1.UninstallResultH\x00R\x0funinstallResult\x12J\n" +
	"\x0etraffic_report\x18\r \x01(\v2!.openproxy.agent.v1.TrafficReportH\x00R\rtrafficReport\x12A\n" +
	"\verror_reply\x18\x0e \x01(\v2\x1e.openproxy.agent.v1.ErrorReplyH\x00R\n" +
	"errorReply\x12D\n" +
	"\fstate_report\x18d \x01(\v2\x1f.openproxy.agent.v1.StateReportH\x00R\vstateReport\x12p\n" +
	"\x1ccheck_reality_targets_result\x18e \x01(\v2-.openproxy.agent.v1.CheckRealityTargetsResultH\x00R\x19checkRealityTargetsResult\x12m\n" +
	"\x1bscan_reality_targets_result\x18f \x01(\v2,.openproxy.agent.v1.ScanRealityTargetsResultH\x00R\x18scanRealityTargetsResultB\x06\n" +
	"\x04body\"\xc7\x04\n" +
	"\rMasterMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\breply_to\x18\x02 \x01(\x04R\areplyTo\x12D\n" +
	"\fhello_result\x18\n" +
	" \x01(\v2\x1f.openproxy.agent.v1.HelloResultH\x00R\vhelloResult\x127\n" +
	"\aupgrade\x18\v \x01(\v2\x1b.openproxy.agent.v1.UpgradeH\x00R\aupgrade\x12=\n" +
	"\tuninstall\x18\f \x01(\v2\x1d.openproxy.agent.v1.UninstallH\x00R\tuninstall\x12A\n" +
	"\verror_reply\x18\r \x01(\v2\x1e.openproxy.agent.v1.ErrorReplyH\x00R\n" +
	"errorReply\x12G\n" +
	"\rdesired_state\x18d \x01(\v2 .openproxy.agent.v1.DesiredStateH\x00R\fdesiredState\x12]\n" +
	"\x15check_reality_targets\x18e \x01(\v2'.openproxy.agent.v1.CheckRealityTargetsH\x00R\x13checkRealityTargets\x12Z\n" +
	"\x14scan_reality_targets\x18f \x01(\v2&.openproxy.agent.v1.ScanRealityTargetsH\x00R\x12scanRealityTargetsB\x06\n" +
	"\x04bodyB\xdd\x01\n" +
	"\x16com.openproxy.agent.v1B\rEnvelopeProtoP\x01ZJgithub.com/yuuuki-creation/open-proxy/agent/internal/pb/openproxy/agent/v1;agentv1\xa2\x02\x03OAX\xaa\x02\x12Openproxy.Agent.V1\xca\x02\x12Openproxy\\Agent\\V1\xe2\x02\x1eOpenproxy\\Agent\\V1\\GPBMetadata\xea\x02\x14Openproxy::Agent::V1b\x06proto3"

var (
	file_openproxy_agent_v1_envelope_proto_rawDescOnce sync.Once
	file_openproxy_agent_v1_envelope_proto_rawDescData []byte
)

func file_openproxy_agent_v1_envelope_proto_rawDescGZIP() []byte {
	file_openproxy_agent_v1_envelope_proto_rawDescOnce.Do(func() {
		file_openproxy_agent_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openproxy_agent_v1_envelope_proto_rawDesc), len(file_openproxy_agent_v1_envelope_proto_rawDesc)))
	})
	return file_openproxy_agent_v1_envelope_proto_rawDescData
}

var file_openproxy_agent_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openproxy_agent_v1_envelope_proto_goTypes = []any{
	(*AgentMessage)(nil),              // 0: openproxy.agent.v1.AgentMessage
	(*MasterMessage)(nil),             // 1: openproxy.agent.v1.MasterMessage
	(*Hello)(nil),                     // 2: openproxy.agent.v1.Hello
	(*UpgradeResult)(nil),             // 3: openproxy.agent.v1.UpgradeResult
	(*UninstallResult)(nil),           // 4: openproxy.agent.v1.UninstallResult
	(*TrafficReport)(nil),             // 5: openproxy.agent.v1.TrafficReport
	(*ErrorReply)(nil),                // 6: openproxy.agent.v1.ErrorReply
	(*StateReport)(nil),               // 7: openproxy.agent.v1.StateReport
	(*CheckRealityTargetsResult)(nil), // 8: openproxy.agent.v1.CheckRealityTargetsResult
	(*ScanRealityTargetsResult)(nil),  // 9: openproxy.agent.v1.ScanRealityTargetsResult
	(*HelloResult)(nil),               // 10: openproxy.agent.v1.HelloResult
	(*Upgrade)(nil),                   // 11: openproxy.agent.v1.Upgrade
	(*Uninstall)(nil),                 // 12: openproxy.agent.v1.Uninstall
	(*DesiredState)(nil),              // 13: openproxy.agent.v1.DesiredState
	(*CheckRealityTargets)(nil),       // 14: openproxy.agent.v1.CheckRealityTargets
	(*ScanRealityTargets)(nil),        // 15: openproxy.agent.v1.ScanRealityTargets
}
var file_openproxy_agent_v1_envelope_proto_depIdxs = []int32{
	2,  // 0: openproxy.agent.v1.AgentMessage.hello:type_name -> openproxy.agent.v1.Hello
	3,  // 1: openproxy.agent.v1.AgentMessage.upgrade_result:type_name -> openproxy.agent.v1.UpgradeResult
	4,  // 2: openproxy.agent.v1.AgentMessage.uninstall_result:type_name -> openproxy.agent.v1.UninstallResult
	5,  // 3: openproxy.agent.v1.AgentMessage.traffic_report:type_name -> openproxy.agent.v1.TrafficReport
	6,  // 4: openproxy.agent.v1.AgentMessage.error_reply:type_name -> openproxy.agent.v1.ErrorReply
	7,  // 5: openproxy.agent.v1.AgentMessage.state_report:type_name -> openproxy.agent.v1.StateReport
	8,  // 6: openproxy.agent.v1.AgentMessage.check_reality_targets_result:type_name -> openproxy.agent.v1.CheckRealityTargetsResult
	9,  // 7: openproxy.agent.v1.AgentMessage.scan_reality_targets_result:type_name -> openproxy.agent.v1.ScanRealityTargetsResult
	10, // 8: openproxy.agent.v1.MasterMessage.hello_result:type_name -> openproxy.agent.v1.HelloResult
	11, // 9: openproxy.agent.v1.MasterMessage.upgrade:type_name -> openproxy.agent.v1.Upgrade
	12, // 10: openproxy.agent.v1.MasterMessage.uninstall:type_name -> openproxy.agent.v1.Uninstall
	6,  // 11: openproxy.agent.v1.MasterMessage.error_reply:type_name -> openproxy.agent.v1.ErrorReply
	13, // 12: openproxy.agent.v1.MasterMessage.desired_state:type_name -> openproxy.agent.v1.DesiredState
	14, // 13: openproxy.agent.v1.MasterMessage.check_reality_targets:type_name -> openproxy.agent.v1.CheckRealityTargets
	15, // 14: openproxy.agent.v1.MasterMessage.scan_reality_targets:type_name -> openproxy.agent.v1.ScanRealityTargets
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_openproxy_agent_v1_envelope_proto_init() }
func file_openproxy_agent_v1_envelope_proto_init() {
	if File_openproxy_agent_v1_envelope_proto != nil {
		return
	}
	file_openproxy_agent_v1_agent_proto_init()
	file_openproxy_agent_v1_stable_proto_init()
	file_openproxy_agent_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_UpgradeResult)(nil),
		(*AgentMessage_UninstallResult)(nil),
		(*AgentMessage_TrafficReport)(nil),
		(*AgentMessage_ErrorReply)(nil),
		(*AgentMessage_StateReport)(nil),
		(*AgentMessage_CheckRealityTargetsResult)(nil),
		(*AgentMessage_ScanRealityTargetsResult)(nil),
	}
	file_openproxy_agent_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*MasterMessage_HelloResult)(nil),
		(*MasterMessage_Upgrade)(nil),
		(*MasterMessage_Uninstall)(nil),
		(*MasterMessage_ErrorReply)(nil),
		(*MasterMessage_DesiredState)(nil),
		(*MasterMessage_CheckRealityTargets)(nil),
		(*MasterMessage_ScanRealityTargets)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openproxy_agent_v1_envelope_proto_rawDesc), len(file_openproxy_agent_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openproxy_agent_v1_envelope_proto_goTypes,
		DependencyIndexes: file_openproxy_agent_v1_envelope_proto_depIdxs,
		MessageInfos:      file_openproxy_agent_v1_envelope_proto_msgTypes,
	}.Build()
	File_openproxy_agent_v1_envelope_proto = out.File
	file_openproxy_agent_v1_envelope_proto_goTypes = nil
	file_openproxy_agent_v1_envelope_proto_depIdxs = nil
}
