// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openproxy/agent/v1/stable.proto

// 稳定消息：主控和 Agent 版本不一致时，仍然要能互相听懂。
// 规则：字段只加不改，不改含义；删字段要 reserved。
// 见 docs/design-docs/protocol.md「兼容规则」。

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CPU 架构，主控据此选择升级用的二进制。
type Arch int32

const (
	Arch_ARCH_UNSPECIFIED Arch = 0
	Arch_ARCH_AMD64       Arch = 1
	Arch_ARCH_ARM64       Arch = 2
)

// Enum value maps for Arch.
var (
	Arch_name = map[int32]string{
		0: "ARCH_UNSPECIFIED",
		1: "ARCH_AMD64",
		2: "ARCH_ARM64",
	}
	Arch_value = map[string]int32{
		"ARCH_UNSPECIFIED": 0,
		"ARCH_AMD64":       1,
		"ARCH_ARM64":       2,
	}
)

func (x Arch) Enum() *Arch {
	p := new(Arch)
	*p = x
	return p
}

func (x Arch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Arch) Descriptor() protoreflect.EnumDescriptor {
	return file_openproxy_agent_v1_stable_proto_enumTypes[0].Descriptor()
}

func (Arch) Type() protoreflect.EnumType {
	return &file_openproxy_agent_v1_stable_proto_enumTypes[0]
}

func (x Arch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Arch.Descriptor instead.
func (Arch) EnumDescriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{0}
}

type HelloResult_Status int32

const (
	HelloResult_STATUS_UNSPECIFIED HelloResult_Status = 0
	HelloResult_STATUS_OK          HelloResult_Status = 1
	// Token 不存在或不匹配：Agent 长退避后重试，不卸载。
	HelloResult_STATUS_INVALID_TOKEN HelloResult_Status = 2
	// 这台服务器已经有一个在线连接：Agent 普通退避后重试。
	HelloResult_STATUS_DUPLICATE_CONNECTION HelloResult_Status = 3
	// 服务器已在面板上删除：Agent 卸载自己。
	HelloResult_STATUS_SERVER_DELETED HelloResult_Status = 4
)

// Enum value maps for HelloResult_Status.
var (
	HelloResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_INVALID_TOKEN",
		3: "STATUS_DUPLICATE_CONNECTION",
		4: "STATUS_SERVER_DELETED",
	}
	HelloResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":          0,
		"STATUS_OK":                   1,
		"STATUS_INVALID_TOKEN":        2,
		"STATUS_DUPLICATE_CONNECTION": 3,
		"STATUS_SERVER_DELETED":       4,
	}
)

func (x HelloResult_Status) Enum() *HelloResult_Status {
	p := new(HelloResult_Status)
	*p = x
	return p
}

func (x HelloResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelloResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_openproxy_agent_v1_stable_proto_enumTypes[1].Descriptor()
}

func (HelloResult_Status) Type() protoreflect.EnumType {
	return &file_openproxy_agent_v1_stable_proto_enumTypes[1]
}

func (x HelloResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelloResult_Status.Descriptor instead.
func (HelloResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{1, 0}
}

type ErrorReply_Code int32

const (
	ErrorReply_CODE_UNSPECIFIED ErrorReply_Code = 0
	// 认识这个请求，但当前不能处理，例如版本不一致时收到非稳定的请求。
	// 完全不认识的消息解析后 body 为空，接收方分不清是请求还是推送，只能忽略，请求方靠超时发现。
	ErrorReply_CODE_UNSUPPORTED ErrorReply_Code = 1
	// 认识，但处理失败。
	ErrorReply_CODE_FAILED ErrorReply_Code = 2
)

// Enum value maps for ErrorReply_Code.
var (
	ErrorReply_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_UNSUPPORTED",
		2: "CODE_FAILED",
	}
	ErrorReply_Code_value = map[string]int32{
		"CODE_UNSPECIFIED": 0,
		"CODE_UNSUPPORTED": 1,
		"CODE_FAILED":      2,
	}
)

func (x ErrorReply_Code) Enum() *ErrorReply_Code {
	p := new(ErrorReply_Code)
	*p = x
	return p
}

func (x ErrorReply_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReply_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_openproxy_agent_v1_stable_proto_enumTypes[2].Descriptor()
}

func (ErrorReply_Code) Type() protoreflect.EnumType {
	return &file_openproxy_agent_v1_stable_proto_enumTypes[2]
}

func (x ErrorReply_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReply_Code.Descriptor instead.
func (ErrorReply_Code) EnumDescriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{9, 0}
}

// Agent 连上后发的第一条消息（请求，主控回 HelloResult）。
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 安装时写进配置的 Token，主控比对哈希。打日志时要隐去。
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Agent 版本，例如 "0.1.0"。和主控版本一致才同步期望状态。
	AgentVersion string `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Arch         Arch   `protobuf:"varint,3,opt,name=arch,proto3,enum=openproxy.agent.v1.Arch" json:"arch,omitempty"`
	// Agent 进程每次启动随机生成；流量上报也带它，主控据此识别 Agent 重启。
	InstanceId uint64 `protobuf:"varint,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// 本地已应用的期望状态版本；没有本地状态时为 0。
	StateVersion uint64 `protobuf:"varint,5,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	// 上次升级失败、换回旧版本时，填当时要升级到的版本；否则为空。
	RolledBackFrom string `protobuf:"bytes,6,opt,name=rolled_back_from,json=rolledBackFrom,proto3" json:"rolled_back_from,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetArch() Arch {
	if x != nil {
		return x.Arch
	}
	return Arch_ARCH_UNSPECIFIED
}

func (x *Hello) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Hello) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *Hello) GetRolledBackFrom() string {
	if x != nil {
		return x.RolledBackFrom
	}
	return ""
}

// 主控对 Hello 的回复。
type HelloResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status HelloResult_Status     `protobuf:"varint,1,opt,name=status,proto3,enum=openproxy.agent.v1.HelloResult_Status" json:"status,omitempty"`
	// 主控版本。
	MasterVersion string `protobuf:"bytes,2,opt,name=master_version,json=masterVersion,proto3" json:"master_version,omitempty"`
	// 版本一致，开始同步期望状态；为 false 时只收发稳定消息。
	Sync          bool `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResult) Reset() {
	*x = HelloResult{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResult) ProtoMessage() {}

func (x *HelloResult) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResult.ProtoReflect.Descriptor instead.
func (*HelloResult) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResult) GetStatus() HelloResult_Status {
	if x != nil {
		return x.Status
	}
	return HelloResult_STATUS_UNSPECIFIED
}

func (x *HelloResult) GetMasterVersion() string {
	if x != nil {
		return x.MasterVersion
	}
	return ""
}

func (x *HelloResult) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

// 主控让 Agent 升级（请求，Agent 回 UpgradeResult）。
type Upgrade struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// 下载路径，例如 "/api/agent/binary/0.2.0/amd64"。Agent 用自己配置的主控地址拼成完整 URL；
	// 只给路径，Token 就不会被发到别的地址。
	DownloadPath string `protobuf:"bytes,2,opt,name=download_path,json=downloadPath,proto3" json:"download_path,omitempty"`
	// 二进制文件的 SHA-256。
	Sha256 []byte `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// 对二进制文件内容的 Ed25519 分离签名，Agent 用内置公钥验证。
	Signature     []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upgrade) Reset() {
	*x = Upgrade{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upgrade) ProtoMessage() {}

func (x *Upgrade) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upgrade.ProtoReflect.Descriptor instead.
func (*Upgrade) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{2}
}

func (x *Upgrade) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Upgrade) GetDownloadPath() string {
	if x != nil {
		return x.DownloadPath
	}
	return ""
}

func (x *Upgrade) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *Upgrade) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Agent 对 Upgrade 的回复。成功后 Agent 补发一次流量上报再退出，由 systemd 拉起新版本。
type UpgradeResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 失败原因；成功时为空。
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeResult) Reset() {
	*x = UpgradeResult{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeResult) ProtoMessage() {}

func (x *UpgradeResult) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeResult.ProtoReflect.Descriptor instead.
func (*UpgradeResult) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{3}
}

func (x *UpgradeResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpgradeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 主控让 Agent 卸载自己（请求，Agent 回 UninstallResult），删除服务器时发。
type Uninstall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uninstall) Reset() {
	*x = Uninstall{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uninstall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uninstall) ProtoMessage() {}

func (x *Uninstall) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uninstall.ProtoReflect.Descriptor instead.
func (*Uninstall) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{4}
}

// Agent 对 Uninstall 的回复。回复后补发一次流量上报，再停掉入站、清理防火墙规则、删除自己。
type UninstallResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 失败原因；成功时为空。
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallResult) Reset() {
	*x = UninstallResult{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallResult) ProtoMessage() {}

func (x *UninstallResult) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallResult.ProtoReflect.Descriptor instead.
func (*UninstallResult) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{5}
}

func (x *UninstallResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UninstallResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 流量上报（推送，每 10 秒一次）。
type TrafficReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 和 Hello 里的 instance_id 相同。
	InstanceId uint64 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// 按「节点 × 用户」的累计流量，只含非零的行。
	Users []*UserTraffic `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	// 服务器网卡的累计流量。
	Network       *NetworkTraffic `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficReport) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *TrafficReport) GetUsers() []*UserTraffic {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *TrafficReport) GetNetwork() *NetworkTraffic {
	if x != nil {
		return x.Network
	}
	return nil
}

// 一个用户在一个节点上的累计流量，从 Agent 进程启动时算起。
type UserTraffic struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 客户端发上来的字节数。
	Uplink uint64 `protobuf:"varint,3,opt,name=uplink,proto3" json:"uplink,omitempty"`
	// 发回客户端的字节数。
	Downlink      uint64 `protobuf:"varint,4,opt,name=downlink,proto3" json:"downlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{7}
}

func (x *UserTraffic) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UserTraffic) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTraffic) GetUplink() uint64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *UserTraffic) GetDownlink() uint64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

// 默认路由所在网卡的累计收发，读自 /proc/net/dev。主控用相邻两次的差算网速和整机流量。
type NetworkTraffic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// /proc/sys/kernel/random/boot_id；变了说明服务器重启过，计数归零。
	BootId string `protobuf:"bytes,1,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	// 网卡名，例如 "eth0"。
	Interface     string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	RxBytes       uint64 `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64 `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkTraffic) Reset() {
	*x = NetworkTraffic{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTraffic) ProtoMessage() {}

func (x *NetworkTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTraffic.ProtoReflect.Descriptor instead.
func (*NetworkTraffic) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkTraffic) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *NetworkTraffic) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *NetworkTraffic) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkTraffic) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

// 请求处理不了时的回复，两个方向都用。
type ErrorReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorReply_Code        `protobuf:"varint,1,opt,name=code,proto3,enum=openproxy.agent.v1.ErrorReply_Code" json:"code,omitempty"`
	// 给人看的说明。
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReply) Reset() {
	*x = ErrorReply{}
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReply) ProtoMessage() {}

func (x *ErrorReply) ProtoReflect() protoreflect.Message {
	mi := &file_openproxy_agent_v1_stable_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReply.ProtoReflect.Descriptor instead.
func (*ErrorReply) Descriptor() ([]byte, []int) {
	return file_openproxy_agent_v1_stable_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorReply) GetCode() ErrorReply_Code {
	if x != nil {
		return x.Code
	}
	return ErrorReply_CODE_UNSPECIFIED
}

func (x *ErrorReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_openproxy_agent_v1_stable_proto protoreflect.FileDescriptor

const file_openproxy_agent_v1_stable_proto_rawDesc = "" +
	"\n" +
	"\x1fopenproxy/agent/v1/stable.proto\x12\x12openproxy.agent.v1\"\xe0\x01\n" +
	"\x05Hello\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12,\n" +
	"\x04arch\x18\x03 \x01(\x0e2\x18.openproxy.agent.v1.ArchR\x04arch\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\x04R\n" +
	"instanceId\x12#\n" +
	"\rstate_version\x18\x05 \x01(\x04R\fstateVersion\x12(\n" +
	"\x10rolled_back_from\x18\x06 \x01(\tR\x0erolledBackFrom\"\x90\x02\n" +
	"\vHelloResult\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.openproxy.agent.v1.HelloResult.StatusR\x06status\x12%\n" +
	"\x0emaster_version\x18\x02 \x01(\tR\rmasterVersion\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\"\x85\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x18\n" +
	"\x14STATUS_INVALID_TOKEN\x10\x02\x12\x1f\n" +
	"\x1bSTATUS_DUPLICATE_CONNECTION\x10\x03\x12\x19\n" +
	"\x15STATUS_SERVER_DELETED\x10\x04\"~\n" +
	"\aUpgrade\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12#\n" +
	"\rdownload_path\x18\x02 \x01(\tR\fdownloadPath\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"5\n" +
	"\rUpgradeResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\v\n" +
	"\tUninstall\"7\n" +
	"\x0fUninstallResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa5\x01\n" +
	"\rTrafficReport\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\x125\n" +
	"\x05users\x18\x02 \x03(\v2\x1f.openproxy.agent.v1.UserTrafficR\x05users\x12<\n" +
	"\anetwork\x18\x03 \x01(\v2\".openproxy.agent.v1.NetworkTrafficR\anetwork\"s\n" +
	"\vUserTraffic\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06uplink\x18\x03 \x01(\x04R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x04 \x01(\x04R\bdownlink\"}\n" +
	"\x0eNetworkTraffic\x12\x17\n" +
	"\aboot_id\x18\x01 \x01(\tR\x06bootId\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x04R\atxBytes\"\xa4\x01\n" +
	"\n" +
	"ErrorReply\x127\n" +
	"\x04code\x18\x01 \x01(\x0e2#.openproxy.agent.v1.ErrorReply.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CODE_UNSUPPORTED\x10\x01\x12\x0f\n" +
	"\vCODE_FAILED\x10\x02*<\n" +
	"\x04Arch\x12\x14\n" +
	"\x10ARCH_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ARCH_AMD64\x10\x01\x12\x0e\n" +
	"\n" +
	"ARCH_ARM64\x10\x02B\xdb\x01\n" +
	"\x16com.openproxy.agent.v1B\vStableProtoP\x01ZJgithub.com/yuuuki-creation/open-proxy/agent/internal/pb/openproxy/agent/v1;agentv1\xa2\x02\x03OAX\xaa\x02\x12Openproxy.Agent.V1\xca\x02\x12Openproxy\\Agent\\V1\xe2\x02\x1eOpenproxy\\Agent\\V1\\GPBMetadata\xea\x02\x14Openproxy::Agent::V1b\x06proto3"

var (
	file_openproxy_agent_v1_stable_proto_rawDescOnce sync.Once
	file_openproxy_agent_v1_stable_proto_rawDescData []byte
)

func file_openproxy_agent_v1_stable_proto_rawDescGZIP() []byte {
	file_openproxy_agent_v1_stable_proto_rawDescOnce.Do(func() {
		file_openproxy_agent_v1_stable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openproxy_agent_v1_stable_proto_rawDesc), len(file_openproxy_agent_v1_stable_proto_rawDesc)))
	})
	return file_openproxy_agent_v1_stable_proto_rawDescData
}

var file_openproxy_agent_v1_stable_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_openproxy_agent_v1_stable_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_openproxy_agent_v1_stable_proto_goTypes = []any{
	(Arch)(0),               // 0: openproxy.agent.v1.Arch
	(HelloResult_Status)(0), // 1: openproxy.agent.v1.HelloResult.Status
	(ErrorReply_Code)(0),    // 2: openproxy.agent.v1.ErrorReply.Code
	(*Hello)(nil),           // 3: openproxy.agent.v1.Hello
	(*HelloResult)(nil),     // 4: openproxy.agent.v1.HelloResult
	(*Upgrade)(nil),         // 5: openproxy.agent.v1.Upgrade
	(*UpgradeResult)(nil),   // 6: openproxy.agent.v1.UpgradeResult
	(*Uninstall)(nil),       // 7: openproxy.agent.v1.Uninstall
	(*UninstallResult)(nil), // 8: openproxy.agent.v1.UninstallResult
	(*TrafficReport)(nil),   // 9: openproxy.agent.v1.TrafficReport
	(*UserTraffic)(nil),     // 10: openproxy.agent.v1.UserTraffic
	(*NetworkTraffic)(nil),  // 11: openproxy.agent.v1.NetworkTraffic
	(*ErrorReply)(nil),      // 12: openproxy.agent.v1.ErrorReply
}
var file_openproxy_agent_v1_stable_proto_depIdxs = []int32{
	0,  // 0: openproxy.agent.v1.Hello.arch:type_name -> openproxy.agent.v1.Arch
	1,  // 1: openproxy.agent.v1.HelloResult.status:type_name -> openproxy.agent.v1.HelloResult.Status
	10, // 2: openproxy.agent.v1.TrafficReport.users:type_name -> openproxy.agent.v1.UserTraffic
	11, // 3: openproxy.agent.v1.TrafficReport.network:type_name -> openproxy.agent.v1.NetworkTraffic
	2,  // 4: openproxy.agent.v1.ErrorReply.code:type_name -> openproxy.agent.v1.ErrorReply.Code
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_openproxy_agent_v1_stable_proto_init() }
func file_openproxy_agent_v1_stable_proto_init() {
	if File_openproxy_agent_v1_stable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openproxy_agent_v1_stable_proto_rawDesc), len(file_openproxy_agent_v1_stable_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openproxy_agent_v1_stable_proto_goTypes,
		DependencyIndexes: file_openproxy_agent_v1_stable_proto_depIdxs,
		EnumInfos:         file_openproxy_agent_v1_stable_proto_enumTypes,
		MessageInfos:      file_openproxy_agent_v1_stable_proto_msgTypes,
	}.Build()
	File_openproxy_agent_v1_stable_proto = out.File
	file_openproxy_agent_v1_stable_proto_goTypes = nil
	file_openproxy_agent_v1_stable_proto_depIdxs = nil
}
