// @generated
// This file is @generated by prost-build.
/// 主控给一台服务器的整份期望状态（推送）。Agent 逐项应用，然后发 StateReport。
/// Agent 把它原样（protobuf 编码）保存在本地，启动时先按它启动。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DesiredState {
    /// 单调递增：取「上一个版本 + 1」和当前毫秒时间戳中的大者。
    #[prost(uint64, tag="1")]
    pub version: u64,
    /// 这台服务器上用得到的用户。
    #[prost(message, repeated, tag="2")]
    pub users: ::prost::alloc::vec::Vec<User>,
    #[prost(message, repeated, tag="3")]
    pub nodes: ::prost::alloc::vec::Vec<Node>,
    #[prost(message, repeated, tag="4")]
    pub exits: ::prost::alloc::vec::Vec<Exit>,
    /// 这台服务器当自建落地机时的 SOCKS5 入站；不当落地机时不设置。
    #[prost(message, optional, tag="5")]
    pub landing: ::core::option::Option<Landing>,
    /// TLS 节点（Hysteria2、AnyTLS）共用的证书；没有 TLS 节点时不设置。
    #[prost(message, optional, tag="6")]
    pub certificate: ::core::option::Option<Certificate>,
}
/// 一个用户的凭据，所有节点通用。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    /// 用户 ID；它的十进制字符串就是 sing-box 和 Mieru 里的用户名。
    #[prost(uint64, tag="1")]
    pub id: u64,
    /// VLESS 用。
    #[prost(string, tag="2")]
    pub uuid: ::prost::alloc::string::String,
    /// Hysteria2、AnyTLS、Mieru 用。
    #[prost(string, tag="3")]
    pub password: ::prost::alloc::string::String,
    /// Shadowsocks 2022 的用户密钥（base64），长度符合加密方式。
    #[prost(string, tag="4")]
    pub ss_key: ::prost::alloc::string::String,
}
/// 一个节点就是一个入站，入站 tag 是 "node-<id>"。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Node {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(uint32, tag="2")]
    pub port: u32,
    /// 能用这个节点的用户，引用 DesiredState.users 里的 ID。
    /// 追踪层只放行这里列出的用户：用户被移除后立即断开，不等入站重建。
    #[prost(uint64, repeated, tag="3")]
    pub user_ids: ::prost::alloc::vec::Vec<u64>,
    /// 流量走哪个落地出口，引用 DesiredState.exits 里的 ID；0 表示直连。
    #[prost(uint64, tag="4")]
    pub exit_id: u64,
    #[prost(oneof="node::Protocol", tags="10, 11, 12, 13, 14")]
    pub protocol: ::core::option::Option<node::Protocol>,
}
/// Nested message and enum types in `Node`.
pub mod node {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Protocol {
        #[prost(message, tag="10")]
        VlessReality(super::VlessReality),
        #[prost(message, tag="11")]
        Hysteria2(super::Hysteria2),
        #[prost(message, tag="12")]
        Anytls(super::AnyTls),
        #[prost(message, tag="13")]
        Shadowsocks2022(super::Shadowsocks2022),
        #[prost(message, tag="14")]
        Mieru(super::Mieru),
    }
}
/// VLESS + REALITY：传输 TCP，flow 固定为 xtls-rprx-vision。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VlessReality {
    /// X25519 私钥，base64 raw url 编码。
    #[prost(string, tag="1")]
    pub private_key: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub short_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 伪装目标，同时作为 server_name。
    #[prost(string, tag="3")]
    pub target_host: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub target_port: u32,
}
/// Hysteria2：使用 DesiredState.certificate。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hysteria2 {
    /// salamander 混淆密码；为空表示不开混淆。
    #[prost(string, tag="1")]
    pub obfs_password: ::prost::alloc::string::String,
    /// 端口跳跃范围，Agent 用 nftables 转发到节点端口；不设置表示不开。
    #[prost(message, optional, tag="2")]
    pub port_hopping: ::core::option::Option<PortRange>,
}
/// 闭区间 \[start, end\]。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PortRange {
    #[prost(uint32, tag="1")]
    pub start: u32,
    #[prost(uint32, tag="2")]
    pub end: u32,
}
/// AnyTLS：只用 TLS，使用 DesiredState.certificate。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AnyTls {
}
/// Shadowsocks 2022，多用户。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Shadowsocks2022 {
    /// 目前固定为 "2022-blake3-aes-128-gcm"。
    #[prost(string, tag="1")]
    pub method: ::prost::alloc::string::String,
    /// 服务端主密钥（base64）。
    #[prost(string, tag="2")]
    pub server_key: ::prost::alloc::string::String,
}
/// Mieru：传输 TCP。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mieru {
}
/// 落地出口：一个 SOCKS5 出站，tag 是 "exit-<id>"。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Exit {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(string, tag="2")]
    pub host: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub port: u32,
    #[prost(string, tag="4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub password: ::prost::alloc::string::String,
}
/// 自建落地机上的 SOCKS5 入站。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Landing {
    #[prost(uint32, tag="1")]
    pub port: u32,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub password: ::prost::alloc::string::String,
    /// 只放行这些来源 IP（用这台落地的节点服务器）；主控生成状态时把服务器地址解析成 IP。
    #[prost(string, repeated, tag="4")]
    pub allowed_source_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// PEM 格式的证书和私钥：有域名的是主控申请的正式证书，没有域名的是主控生成的自签证书。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Certificate {
    /// 证书链，服务器证书在前。
    #[prost(string, tag="1")]
    pub cert_pem: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub key_pem: ::prost::alloc::string::String,
}
/// Agent 应用完一份期望状态后的报告（推送）。连接成功、同步开始时也发一次。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateReport {
    /// 已经处理完的期望状态版本（含失败项），不表示全部成功。
    #[prost(uint64, tag="1")]
    pub applied_version: u64,
    /// 应用失败的项：这些项保持原样，其他项照常生效。
    #[prost(message, repeated, tag="2")]
    pub failures: ::prost::alloc::vec::Vec<ApplyFailure>,
}
/// 一项应用失败。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplyFailure {
    #[prost(enumeration="apply_failure::Item", tag="1")]
    pub item: i32,
    #[prost(uint64, tag="2")]
    pub id: u64,
    /// 给管理员看的原因，例如「端口 443 被占用」。
    #[prost(string, tag="3")]
    pub reason: ::prost::alloc::string::String,
}
/// Nested message and enum types in `ApplyFailure`.
pub mod apply_failure {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Item {
        Unspecified = 0,
        /// id 是节点 ID。
        Node = 1,
        /// id 是出口 ID。
        Exit = 2,
        /// id 为 0。
        Landing = 3,
        /// id 为 0。
        Certificate = 4,
        /// id 是节点 ID。
        PortHopping = 5,
    }
    impl Item {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "ITEM_UNSPECIFIED",
                Self::Node => "ITEM_NODE",
                Self::Exit => "ITEM_EXIT",
                Self::Landing => "ITEM_LANDING",
                Self::Certificate => "ITEM_CERTIFICATE",
                Self::PortHopping => "ITEM_PORT_HOPPING",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ITEM_UNSPECIFIED" => Some(Self::Unspecified),
                "ITEM_NODE" => Some(Self::Node),
                "ITEM_EXIT" => Some(Self::Exit),
                "ITEM_LANDING" => Some(Self::Landing),
                "ITEM_CERTIFICATE" => Some(Self::Certificate),
                "ITEM_PORT_HOPPING" => Some(Self::PortHopping),
                _ => None,
            }
        }
    }
}
/// 检测管理员选中的 REALITY 伪装目标（请求，超时 1 分钟）。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckRealityTargets {
    /// "host" 或 "host:port"，不写端口时是 443。
    #[prost(string, repeated, tag="1")]
    pub targets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Agent 对 CheckRealityTargets 的回复。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckRealityTargetsResult {
    #[prost(message, repeated, tag="1")]
    pub results: ::prost::alloc::vec::Vec<RealityTargetCheck>,
}
/// 一个目标的检测结果，在节点服务器上测得。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RealityTargetCheck {
    #[prost(string, tag="1")]
    pub target: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub tls13: bool,
    #[prost(bool, tag="3")]
    pub h2: bool,
    #[prost(uint32, tag="4")]
    pub latency_ms: u32,
    #[prost(bool, tag="5")]
    pub certificate_valid: bool,
    /// 连不上等错误；为空表示检测完成，看上面几项。
    #[prost(string, tag="6")]
    pub error: ::prost::alloc::string::String,
}
/// 在服务器上扫描可用的 REALITY 伪装目标（请求，超时 20 分钟）。慢速、低并发。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScanRealityTargets {
    /// 要扫的网段，例如 "203.0.113.0/24"。
    #[prost(string, tag="1")]
    pub cidr: ::prost::alloc::string::String,
    /// 同时扫描的地址数。
    #[prost(uint32, tag="2")]
    pub concurrency: u32,
    /// 每秒最多发起的连接数。
    #[prost(uint32, tag="3")]
    pub max_per_second: u32,
}
/// Agent 对 ScanRealityTargets 的回复，扫描结束时一次性返回。整体失败时改回 ErrorReply。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScanRealityTargetsResult {
    #[prost(message, repeated, tag="1")]
    pub candidates: ::prost::alloc::vec::Vec<RealityScanCandidate>,
}
/// 一个支持 TLS 1.3 和 H2 的候选目标。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RealityScanCandidate {
    #[prost(string, tag="1")]
    pub ip: ::prost::alloc::string::String,
    /// 证书里的域名。
    #[prost(string, tag="2")]
    pub domain: ::prost::alloc::string::String,
    /// 证书签发者。
    #[prost(string, tag="3")]
    pub issuer: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub latency_ms: u32,
}
/// Agent 连上后发的第一条消息（请求，主控回 HelloResult）。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    /// 安装时写进配置的 Token，主控比对哈希。打日志时要隐去。
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    /// Agent 版本，例如 "0.1.0"。和主控版本一致才同步期望状态。
    #[prost(string, tag="2")]
    pub agent_version: ::prost::alloc::string::String,
    #[prost(enumeration="Arch", tag="3")]
    pub arch: i32,
    /// Agent 进程每次启动随机生成；流量上报也带它，主控据此识别 Agent 重启。
    #[prost(uint64, tag="4")]
    pub instance_id: u64,
    /// 本地已应用的期望状态版本；没有本地状态时为 0。
    #[prost(uint64, tag="5")]
    pub state_version: u64,
    /// 上次升级失败、换回旧版本时，填当时要升级到的版本；否则为空。
    #[prost(string, tag="6")]
    pub rolled_back_from: ::prost::alloc::string::String,
}
/// 主控对 Hello 的回复。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HelloResult {
    #[prost(enumeration="hello_result::Status", tag="1")]
    pub status: i32,
    /// 主控版本。
    #[prost(string, tag="2")]
    pub master_version: ::prost::alloc::string::String,
    /// 版本一致，开始同步期望状态；为 false 时只收发稳定消息。
    #[prost(bool, tag="3")]
    pub sync: bool,
}
/// Nested message and enum types in `HelloResult`.
pub mod hello_result {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Status {
        Unspecified = 0,
        Ok = 1,
        /// Token 不存在或不匹配：Agent 长退避后重试，不卸载。
        InvalidToken = 2,
        /// 这台服务器已经有一个在线连接：Agent 普通退避后重试。
        DuplicateConnection = 3,
        /// 服务器已在面板上删除：Agent 卸载自己。
        ServerDeleted = 4,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "STATUS_UNSPECIFIED",
                Self::Ok => "STATUS_OK",
                Self::InvalidToken => "STATUS_INVALID_TOKEN",
                Self::DuplicateConnection => "STATUS_DUPLICATE_CONNECTION",
                Self::ServerDeleted => "STATUS_SERVER_DELETED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
                "STATUS_OK" => Some(Self::Ok),
                "STATUS_INVALID_TOKEN" => Some(Self::InvalidToken),
                "STATUS_DUPLICATE_CONNECTION" => Some(Self::DuplicateConnection),
                "STATUS_SERVER_DELETED" => Some(Self::ServerDeleted),
                _ => None,
            }
        }
    }
}
/// 主控让 Agent 升级（请求，Agent 回 UpgradeResult）。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Upgrade {
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
    /// 下载路径，例如 "/api/agent/binary/0.2.0/amd64"。Agent 用自己配置的主控地址拼成完整 URL；
    /// 只给路径，Token 就不会被发到别的地址。
    #[prost(string, tag="2")]
    pub download_path: ::prost::alloc::string::String,
    /// 二进制文件的 SHA-256。
    #[prost(bytes="vec", tag="3")]
    pub sha256: ::prost::alloc::vec::Vec<u8>,
    /// 对二进制文件内容的 Ed25519 分离签名，Agent 用内置公钥验证。
    #[prost(bytes="vec", tag="4")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// Agent 对 Upgrade 的回复。成功后 Agent 补发一次流量上报再退出，由 systemd 拉起新版本。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpgradeResult {
    #[prost(bool, tag="1")]
    pub ok: bool,
    /// 失败原因；成功时为空。
    #[prost(string, tag="2")]
    pub error: ::prost::alloc::string::String,
}
/// 主控让 Agent 卸载自己（请求，Agent 回 UninstallResult），删除服务器时发。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Uninstall {
}
/// Agent 对 Uninstall 的回复。回复后补发一次流量上报，再停掉入站、清理防火墙规则、删除自己。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UninstallResult {
    #[prost(bool, tag="1")]
    pub ok: bool,
    /// 失败原因；成功时为空。
    #[prost(string, tag="2")]
    pub error: ::prost::alloc::string::String,
}
/// 流量上报（推送，每 10 秒一次）。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrafficReport {
    /// 和 Hello 里的 instance_id 相同。
    #[prost(uint64, tag="1")]
    pub instance_id: u64,
    /// 按「节点 × 用户」的累计流量，只含非零的行。
    #[prost(message, repeated, tag="2")]
    pub users: ::prost::alloc::vec::Vec<UserTraffic>,
    /// 服务器网卡的累计流量。
    #[prost(message, optional, tag="3")]
    pub network: ::core::option::Option<NetworkTraffic>,
}
/// 一个用户在一个节点上的累计流量，从 Agent 进程启动时算起。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserTraffic {
    #[prost(uint64, tag="1")]
    pub node_id: u64,
    #[prost(uint64, tag="2")]
    pub user_id: u64,
    /// 客户端发上来的字节数。
    #[prost(uint64, tag="3")]
    pub uplink: u64,
    /// 发回客户端的字节数。
    #[prost(uint64, tag="4")]
    pub downlink: u64,
}
/// 默认路由所在网卡的累计收发，读自 /proc/net/dev。主控用相邻两次的差算网速和整机流量。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkTraffic {
    /// /proc/sys/kernel/random/boot_id；变了说明服务器重启过，计数归零。
    #[prost(string, tag="1")]
    pub boot_id: ::prost::alloc::string::String,
    /// 网卡名，例如 "eth0"。
    #[prost(string, tag="2")]
    pub interface: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub rx_bytes: u64,
    #[prost(uint64, tag="4")]
    pub tx_bytes: u64,
}
/// 请求处理不了时的回复，两个方向都用。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorReply {
    #[prost(enumeration="error_reply::Code", tag="1")]
    pub code: i32,
    /// 给人看的说明。
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `ErrorReply`.
pub mod error_reply {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Code {
        Unspecified = 0,
        /// 认识这个请求，但当前不能处理，例如版本不一致时收到非稳定的请求。
        /// 完全不认识的消息解析后 body 为空，接收方分不清是请求还是推送，只能忽略，请求方靠超时发现。
        Unsupported = 1,
        /// 认识，但处理失败。
        Failed = 2,
    }
    impl Code {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "CODE_UNSPECIFIED",
                Self::Unsupported => "CODE_UNSUPPORTED",
                Self::Failed => "CODE_FAILED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CODE_UNSPECIFIED" => Some(Self::Unspecified),
                "CODE_UNSUPPORTED" => Some(Self::Unsupported),
                "CODE_FAILED" => Some(Self::Failed),
                _ => None,
            }
        }
    }
}
/// CPU 架构，主控据此选择升级用的二进制。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Arch {
    Unspecified = 0,
    Amd64 = 1,
    Arm64 = 2,
}
impl Arch {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ARCH_UNSPECIFIED",
            Self::Amd64 => "ARCH_AMD64",
            Self::Arm64 => "ARCH_ARM64",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARCH_UNSPECIFIED" => Some(Self::Unspecified),
            "ARCH_AMD64" => Some(Self::Amd64),
            "ARCH_ARM64" => Some(Self::Arm64),
            _ => None,
        }
    }
}
/// Agent 发给主控的消息。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentMessage {
    /// 发送方自增的消息 ID，从 1 开始；两个方向各自计数。
    #[prost(uint64, tag="1")]
    pub id: u64,
    /// 回复时填对方那条请求的 id；不是回复填 0。
    #[prost(uint64, tag="2")]
    pub reply_to: u64,
    /// 编号 10–99 给稳定消息，100 起给其他消息。
    #[prost(oneof="agent_message::Body", tags="10, 11, 12, 13, 14, 100, 101, 102")]
    pub body: ::core::option::Option<agent_message::Body>,
}
/// Nested message and enum types in `AgentMessage`.
pub mod agent_message {
    /// 编号 10–99 给稳定消息，100 起给其他消息。
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag="10")]
        Hello(super::Hello),
        #[prost(message, tag="11")]
        UpgradeResult(super::UpgradeResult),
        #[prost(message, tag="12")]
        UninstallResult(super::UninstallResult),
        #[prost(message, tag="13")]
        TrafficReport(super::TrafficReport),
        #[prost(message, tag="14")]
        ErrorReply(super::ErrorReply),
        #[prost(message, tag="100")]
        StateReport(super::StateReport),
        #[prost(message, tag="101")]
        CheckRealityTargetsResult(super::CheckRealityTargetsResult),
        #[prost(message, tag="102")]
        ScanRealityTargetsResult(super::ScanRealityTargetsResult),
    }
}
/// 主控发给 Agent 的消息。
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MasterMessage {
    /// 发送方自增的消息 ID，从 1 开始；两个方向各自计数。
    #[prost(uint64, tag="1")]
    pub id: u64,
    /// 回复时填对方那条请求的 id；不是回复填 0。
    #[prost(uint64, tag="2")]
    pub reply_to: u64,
    /// 编号 10–99 给稳定消息，100 起给其他消息。
    #[prost(oneof="master_message::Body", tags="10, 11, 12, 13, 100, 101, 102")]
    pub body: ::core::option::Option<master_message::Body>,
}
/// Nested message and enum types in `MasterMessage`.
pub mod master_message {
    /// 编号 10–99 给稳定消息，100 起给其他消息。
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag="10")]
        HelloResult(super::HelloResult),
        #[prost(message, tag="11")]
        Upgrade(super::Upgrade),
        #[prost(message, tag="12")]
        Uninstall(super::Uninstall),
        #[prost(message, tag="13")]
        ErrorReply(super::ErrorReply),
        #[prost(message, tag="100")]
        DesiredState(super::DesiredState),
        #[prost(message, tag="101")]
        CheckRealityTargets(super::CheckRealityTargets),
        #[prost(message, tag="102")]
        ScanRealityTargets(super::ScanRealityTargets),
    }
}
// @@protoc_insertion_point(module)
